Update pick documentation
Ensembl/public-plugins pull request #649
Opened 2023-01-11 11:51 UTC by olaaustine

[ENSVAR-5409](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5409)
Waiting for #https://github.com/Ensembl/ensembl-variation/pull/942 and #https://github.com/Ensembl/ensembl-vep/pull/1336 to be merged

2023-01-17 11:33 UTC, ens-ap5 requested changes
Small tweaks required - can you get them done before the end of this week so we can merge them into the new release?

2023-01-17 11:33 UTC, ens-ap5 commented on docs/htdocs/info/docs/tools/vep/script/vep_other.html
>        <p>This is the option
Please also delete "This is the option", as it makes no sense without the other half of the sentence.

2023-01-17 11:33 UTC, ens-ap5 commented on docs/htdocs/info/docs/tools/vep/vep_formats.html
> +        <li><a href="http://www.ensembl.org/info/genome/genebuild/mane.html">MANE Plus Clinical transcript status</a></li>
Is this information only relevant to the www site? If so, please change the protocol to https - if not, make it a relative link.

2023-01-17 11:33 UTC, ens-ap5 commented on docs/htdocs/info/docs/tools/vep/script/vep_other.html
>          <li>canonical status of transcript</li>
Is this information only relevant to the www site? If so, please change the protocol to https - if not, make it a relative link.

2023-01-17 16:35 UTC, nuno-agostinho approved these changes
All seems good to me!

2023-01-23 11:18 UTC, ens-ap5 commented on docs/htdocs/info/docs/tools/vep/vep_formats.html
> +        <li><a href="http://www.ensembl.org/info/genome/genebuild/mane.html">MANE Plus Clinical transcript status</a></li>
I don't see what's changed here - it should either be "https://www.ensembl.org/info/genome/genebuild/mane.html" or "/info/genome/genebuild/mane.html"

2023-01-23 11:19 UTC, ens-ap5 requested changes
Not all requested changes seem to have been implemented.

2023-01-23 11:29 UTC, nuno-agostinho commented
Hey @ens-ap5, @olaaustine is currently on leave so I updated the PR with the changes you mentioned. I used relative links for consistency with the rest of the file.

The PRs mentioned in the description were already merged, so you can please merge this PR if you find it fine now. Tell me otherwise.

Thanks! 😊

2023-01-23 11:40 UTC, ens-ap5 approved these changes

2023-01-23 11:40 UTC, merged