Public docs update (e110) - VEP
Ensembl/public-plugins pull request #678
Opened 2023-04-17 11:07 UTC by nakib103

2023-04-19 10:39 UTC, nuno-agostinho requested changes
Hey @nakib103, thanks for the update!

I noticed some plugin documentations was not the best, so I created a PR to improve on this: https://github.com/Ensembl/VEP_plugins/pull/598.

Also, https://github.com/Ensembl/VEP_plugins/pull/595 will change the docs for PON plugin, so we have to wait until that is merged before making this PR ready to merge.

2023-05-09 10:03 UTC, nuno-agostinho commented
Hey @nakib103, the previous PRs were already merged. However, PR Ensembl/VEP_plugins#601 also impacts VEP plugin docs. Maybe we can wait until this is merged to update plugin docs, but tell me if you think otherwise. Thanks!

2023-05-09 10:16 UTC, nakib103 commented
Yes, I will wait for that PR to be merged and re-generate the plugin docs.

2023-05-23 08:22 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_download.html
> +        <li><a href="//github.com/Ensembl/VEP_plugins/blob/release/[[SPECIESDEFS::ENSEMBL_VERSION]]/MaveDB.pm" rel="external">MaveDB</a> - adds information from MaveDB, a database that contains multi
```suggestion
        <li><a href="//github.com/Ensembl/VEP_plugins/blob/release/[[SPECIESDEFS::ENSEMBL_VERSION]]/MaveDB.pm" rel="external">MaveDB</a> - adds information from MaveDB, a database that holds experimentally determined measures of variant effect</li>
```

2023-05-23 08:58 UTC, nuno-agostinho approved these changes
Looks good to me, thanks @nakib103!

2023-05-23 10:32 UTC, merged