Improve VEP options table
Ensembl/public-plugins pull request #699
Opened 2023-06-09 11:22 UTC by nuno-agostinho

Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html#opt_summary

- Fix table overflow by breaking words in `pre` tags
- Add background colour to distinguish global populations in `--freq_pop`
- Add missing column to a specific row

2023-06-12 08:47 UTC, nakib103 requested changes

2023-06-12 08:49 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +pre {
What do you mean by breaking?

2023-06-12 10:54 UTC, nakib103 commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +pre {
the text in first column breaks inconveniently if the view port is small - 
![image](https://github.com/Ensembl/public-plugins/assets/12125986/6bbc41c9-fdf2-4951-b03b-7748d9edebd9)

2023-06-12 12:20 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +pre {
Confirmed that this only works on Safari, but not Chrome or Firefox.

The issue is related with the boxes of class `info` in the table: every time we change the window size, a new width is calculated for an object with class `info`, so maybe there is some CSS style or JS script we need to override... or maybe replace `info` with a more appropriate class?

I will look more into this later.

2023-06-15 11:20 UTC, nakib103 commented
@jyothishnt , it does not need to go into e110.

2023-11-08 13:01 UTC, veidenberg commented
Just a heads up, we are about to branch for e111 (so main branch will go to e112 after that).

2023-11-08 13:42 UTC, nakib103 commented
Hi @veidenberg, we are not expecting to have it in e111.

2024-01-04 12:08 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +pre {
Now fixed! :)

2024-01-05 11:12 UTC, nakib103 approved these changes
LGTM!~

2024-01-16 11:15 UTC, merged