VEP: clearly document that any species/assembly can be run in CLI (e111)
Ensembl/public-plugins pull request #715
Opened 2023-07-28 17:38 UTC by nuno-agostinho

[ENSVAR-5748](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5748)

Test in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/index.html

2023-08-08 10:13 UTC, jgtate commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> +  for details. <p/>
```suggestion
  for details. </p>
```

2023-08-08 10:13 UTC, jgtate commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> +  (without <kbd>_rm</kbd> or <kbd>_sm</kbd> in the name) sequences. <p/>
```suggestion
  (without <kbd>_rm</kbd> or <kbd>_sm</kbd> in the name) sequences. </p>
```

2023-08-08 10:18 UTC, jgtate commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> +      <p><b>GFF file</b><p/>
```suggestion
      <p><b>GFF file</b></p>
```

2023-08-08 10:18 UTC, jgtate commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> +      <p><b>GTF file</b><p/>
```suggestion
      <p><b>GTF file</b></p>
```

2023-08-14 15:46 UTC, nakib103 requested changes

2023-08-14 15:46 UTC, nakib103 commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> +        offline mode or if the desired species or assembly is not part of the
A link to `--offline` mode is better here - 

```suggestion
        <a href="vep_options.html#opt_offline">--offline</a> mode or if the desired species or assembly is not part of the
```

2023-08-14 16:06 UTC, nakib103 approved these changes
Looks good, thanks Nuno!

2023-08-15 10:10 UTC, merged