Document new VEP option --individual_zyg (e111)
Ensembl/public-plugins pull request #726
Opened 2023-09-20 08:22 UTC by dglemos

New option available for release 111
[ENSVAR-4523](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4523)

Sandbox: http://wp-np2-11.ebi.ac.uk:7040/info/docs/tools/vep/script/vep_options.html#output

2023-09-20 08:40 UTC, nuno-agostinho requested changes
Hey @dglemos, thanks for the update! I think it is only missing information on incompatible options, but seems fine otherwise.

2023-09-20 08:40 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +      <td>&nbsp;</td>
Mention incompatibility with `--individual`:

```suggestion
      <td>
        <div style="padding:2px 0px"><a href="#opt_individual">--individual</a></div>
      </td>
```

2023-09-20 08:40 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
>          <div style="padding:2px 0px"><a href="#opt_minimal">--minimal</a></div>
Mention incompatibility with `--individual_zyg`

```suggestion
        <div style="padding:2px 0px"><a href="#opt_minimal">--minimal</a></div>
        <div style="padding:2px 0px"><a href="#opt_individual_zyg">--individual_zyg</a></div>
```

2023-09-20 10:30 UTC, nuno-agostinho approved these changes
Thank you for the changes, @dglemos!

2023-09-26 10:20 UTC, jgtate commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +        <div style="padding:2px 0px"><a href="#opt_individual_zyg">--individual_zyg</a>
```suggestion
        <div style="padding:2px 0px"><a href="#opt_individual_zyg">--individual_zyg</a></div>
```

2023-09-26 10:23 UTC, merged