Update docs to note changes in --mane --mane_select flags (e113)
Ensembl/public-plugins pull request #764
Opened 2024-02-08 10:30 UTC by nakib103

sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html#opt_mane

2024-03-12 11:46 UTC, veidenberg commented
@nakib103 is this PR still relevant for e112?

2024-03-15 09:21 UTC, jamie-m-a commented
Hi @veidenberg Nakib is off until next week - he should be able to respond on Monday.

2024-06-04 10:42 UTC, nuno-agostinho requested changes
Hey @nakib103, thanks for the update. I left a couple of small suggestions.

2024-06-04 10:42 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +        transcript for the gene. If <a href="#opt_cache">--cache</a> or <a href="#opt_database">--database</a> annotation source is used the alternative stable id is also added.
```suggestion
        transcript for the gene. If <a href="#opt_cache">--cache</a> or <a href="#opt_database">--database</a> annotation source is used, the alternative transcript stable ID is also added. 
```

2024-06-04 10:42 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_options.html
> +        transcript for the gene. If <a href="#opt_cache">--cache</a> or <a href="#opt_database">--database</a> annotation source is used the alternative stable id is also added.
```suggestion
        transcript for the gene. If <a href="#opt_cache">--cache</a> or <a href="#opt_database">--database</a> annotation source is used, the alternative transcript stable ID is also added. 
```

2024-06-04 10:45 UTC, nuno-agostinho approved these changes
Looks good to me, thanks @nakib103!

2024-06-04 11:02 UTC, merged