Updating variation docs
Ensembl/public-plugins pull request #780
Opened 2024-03-16 16:46 UTC by jamie-m-a

Number of updates to various docs:

Details to follow...

2024-03-18 15:23 UTC, jamie-m-a commented on ensembl/htdocs/info/genome/variation/species/populations.html
> +      <h3>Population from <a href="https://togovar.biosciencedbc.jp/doc/datasets/gem_j_wga" target="_blank" style="text-decoration:none">GEM-J</a></h3>
Agreed, fixed. It was generated by the script so probably an update needed.

2024-03-18 16:14 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
> +<tr class="bg1 plugin_row" data-category="pathogenicity_predictions"><td><div style="font-weight:bold"><a rel="external" href="https://github.com/Ensembl/VEP_plugins/blob/release/[[SPECIESDEFS::ENSEM
Very strange don't know what happened here, I pulled from the repo after Nuno's alpha PRs were merged, in order to get the latest version of the text. I think this was also affected by whatever broke the plugin on the live site.

2024-03-18 16:38 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_download.html
> +      <ul>
Added

2024-03-18 16:49 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/online/input.html
> +                      are correctly sorted</li>
Changed

2024-03-19 09:29 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
> +<tr class="bg1 plugin_row" data-category="pathogenicity_predictions"><td><div style="font-weight:bold"><a rel="external" href="https://github.com/Ensembl/VEP_plugins/blob/release/[[SPECIESDEFS::ENSEM
Reverted to version with correct licence info

2024-03-19 09:31 UTC, jamie-m-a commented on ensembl/htdocs/info/genome/variation/species/populations.html
> +      <h3>Populations from  the <a href="https://evs.gs.washington.edu/EVS/" target="_blank" style="text-decoration:none">NHLBI Exome Sequencing Project</a></h3>
Yes both the official sites seem to have expired, will revert to dbGAP.

2024-03-19 16:01 UTC, nuno-agostinho requested changes
Hi @jamie-m-a, thanks for the PR! I put some suggestions to improve the documentation.

Please tell me if you need help or clarification regarding any of my comments.

2024-03-19 20:35 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
>        <tr>
Thanks Nuno - I ran versus our server but I guess this gets added to the meta after handover, I'll add a not to the process. Will update our notes.
In fact looks like it was only added to core DB for 112, not present in 111.

2024-03-19 20:39 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
Will check

2024-03-19 20:39 UTC, jamie-m-a commented on ensembl/htdocs/info/genome/variation/species/sources_documentation.html
> +            <div class="vdoc_example_style"></div>
Checking this, there were a lot of changes, not sure why they were made

2024-03-20 13:44 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_cache.html
>        <tr>
Was run from release/112 originally, not sure why it didn't grab that update, but yes have rerun after pulling again -  think it looks good now.

2024-03-20 13:45 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
Was run from release/112 originally, not sure why it didn't grab that update, but yes have rerun after pulling again -  think it looks good now.

2024-03-20 14:17 UTC, jamie-m-a commented on ensembl/htdocs/info/genome/variation/species/sources_documentation.html
> +            <div class="vdoc_example_style"></div>
Yea looks like all the VCF-only species had the examples removed and not replaced (script probably deletes existing example but can't graba. replacement correctly for VCF-only).

2024-03-20 15:38 UTC, jamie-m-a commented on docs/htdocs/info/docs/tools/vep/vep_faq.html
> +<p>&nbsp;</p>
Good point, I'll move it

2024-03-22 07:58 UTC, jamie-m-a commented on ensembl/htdocs/info/genome/variation/species/sources_documentation.html
> +            <div class="vdoc_example_style"></div>
These have been added back in now

2024-03-22 15:16 UTC, jamie-m-a commented
This one is ok to go in now - all comments addressed, but Nuno is on leave until after Easter so can't update his requested change.

2024-03-26 11:17 UTC, merged