Notes for the exclude predicted
Ensembl/public-plugins pull request #798
Opened 2024-06-12 08:44 UTC by olaaustine

[ENSVAR-6372](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6372)

2024-06-12 08:54 UTC, nuno-agostinho requested changes

2024-06-12 08:54 UTC, nuno-agostinho commented on docs/htdocs/info/docs/tools/vep/script/vep_other.html
> +  <p>If you prefer to exclude predicted RefSeq transcripts (those with identifiers beginning with "XM_" or "XR_") use <a href="vep_options.html#opt_exclude_predicted">--exclude_predicted</a>.<br>Only
```suggestion
  <p>If you prefer to exclude predicted RefSeq transcripts (those with identifiers beginning with "XM_" or "XR_") use <a href="vep_options.html#opt_exclude_predicted">--exclude_predicted</a>.<br>Only available for human on the GRCh38 assembly.</p>
```

2024-06-12 08:55 UTC, nuno-agostinho approved these changes
Looks good to me, thanks @olaaustine!

2024-06-12 09:08 UTC, sarahhunt commented
@olaaustine - this isn't quite right. The option works to remove predicted RefSeq transcipts for all species (dog, mouse, etc) but we don't support predicted RefSeq transcipts for GRCh37.

We could document that here
http://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq

2024-06-17 13:51 UTC, sarahhunt commented
Looks good - thanks Ola!

2024-06-18 10:20 UTC, merged